### ISSUE TITLE
Manual project setup guide link broken

### ISSUE THREAD

**Issue by riclima** [django-danceschool/django-danceschool#104]
URL http://leetucker.net/django-danceschool/danceschool_default_setup.zip at https://django-danceschool.readthedocs.io/en/latest/installation_manual.html#introduction 404s:

```sh
curl -s -I http://leetucker.net/django-danceschool/danceschool_default_setup.zip | head -n 1
```

Output:
```
HTTP/1.1 404 Not Found
```

**Comment by leetucker** [comment]
@kirkalicious: You are correct, this is supposed to be the URL from the new development repository.  I have just corrected it in the dev branch and I'll push it to master later today.

**Comment by afs2015** [comment]
@leetucker: Was this issue resolved? If so we should mark this ticket as closed.

**Comment by afs2015** [comment]
@ADubhlaoich confirmed this as resolved. Marking as closed.
