### ISSUE TITLE
Broken link to documentation in README.rst

### ISSUE THREAD

**Issue by afs2015** [django-danceschool/django-danceschool#106]
Under the link in "For more detailed instructions, and for a discussion of possible issues that may arise, see the [Documentation](https://django-danceschool.readthedocs.io/en/latest/installation.html#development-installation)." the link Documentation goes to a broken page.

@leetucker [is this the correct page](https://django-danceschool.readthedocs.io/en/latest/installation_development.html) it is supposed to go to? If so the pull request which will be listed below should address this.

**Comment by leetucker** [comment]
I think that this is all set with the recent pull requests.  Thanks for catching this, my bad for neglecting to correct the URL when the documentation layout changed!
