### ISSUE TITLE
Application crashes when using Square sandbox values

### ISSUE THREAD

**Issue by riclima** [django-danceschool/django-danceschool#110]
When using the values provided by Square for [sandbox](https://docs.connect.squareup.com/testing/sandbox) testing, the response from Square's API after a registration contains strings too big for the transactionId and locationId in the model (limited at 50), causing the application to crash.

The solution is super simple, just increase the size of these fields. I'll make a pull request it.

**Comment by leetucker** [comment]
I can make this change quickly, any idea how big we need those fields to be?  My developer account sandbox credentials appear to be well under 50 characters, so I don't have a point of reference.

**Comment by riclima** [comment]
It just occurred to me that I think the issue is only on the transactionID, as the sandbox locations are also under 50 characters. In our patch I bumped it to 100 as a quick fix, but I just looked into our records and the transactionIds for sandbox transactions seem to be exactly 56 characters long.

**Comment by leetucker** [comment]
OK I just changed them both to 100 to be safe, and committed it to the dev branch.  The change will be pushed in the next release.

**Comment by afs2015** [comment]
@leetucker: Was this updated in the last release? If so @riclima do you mind confirming this is fixed and closing the ticket if it is? Thanks!

**Comment by afs2015** [comment]
Marking this as closed.
