### ISSUE TITLE
Setupschool does not use the new staff_list template when initializing the instructor page

### ISSUE THREAD

**Issue by benjwrdill** [django-danceschool/django-danceschool#114]
When the setupschool wizard is adding the instructor page, we use `core/instructor_list.html` as the template, which was renamed to `core/staff_list.html` in 460fcc3b42ba46cfa743a29479bf3f35603f7877.

For reasons I don't understand, when logged in as an unpriveleged user or viewing as a guest, the instructor list still functions as intended (I assume by falling back to a default template). When logged in as a user that can manage instructors, the following error is thrown:
```
Reverse for 'core_instructor_changelist' not found. 'core_instructor_changelist' is not a valid view function or pattern name.
```

**Comment by leetucker** [comment]
@benjwrdill: Just to confirm, is this corrected by the pull request that I just merged?

**Comment by benjwrdill** [comment]
@leetucker Yes, though there might be some issues lurking in setupschool caused by the change of instructor -> polymorphic staff member that I haven't caught yet.

**Comment by afs2015** [comment]
@benjwrdill: Have you caught any additional issues? Otherwise I will mark this ticket as closed. Regardless thank you for creating this issue and bringing the setupschool bug to our attention.

**Comment by leetucker** [comment]
I think we can safely close this for now.  If any additional issues come up re: instructor being generalized to staff member, we can reopen the issue.
