### ISSUE TITLE
Bug: School Stats - Most Popular Vouchers Broken

### ISSUE THREAD

**Issue by afs2015** [django-danceschool/django-danceschool#119]
As [seen in this picture](https://imgur.com/a/Xz2Pds4) currently the school stats page is broken for displaying **Most Popular Vouchers** because `e.voucherId` and `e.description` are returned Undefined.

I'm assuming the fix has to be done in `vouchers/templates/stats/schoolstats_voucherusage.html` in the relevant ajax calls.

I believe this issue is currently the output of the JSON does not match what the code asks. Our JSON returns `e.name` and `e.counter` whereas the current tableData looks for `e.voucherId`, `e.description` and `e.counter`.

```
var tableData = '';
  
    	jsonData.forEach(function(e) {
	        tableData += '<tr><td>' + e.voucherId + '</td><td>' + e.description + '</td><td>' + e.counter + '</td></tr>';
    	});
```

JSON output for our website, 
```
[{"vouchers": 0, "count": 7283}, {"vouchers": 1, "count": 950}, {"vouchers": 2, "count": 40}, {"vouchers": 3, "count": 1}, {"vouchers": 4, "count": 1}]
```

**Comment by afs2015** [comment]
[There are a bunch of errors](https://imgur.com/a/VrixdlQ) that show up in the Console when inspecting in Google Chrome that may be relevant.

**Comment by afs2015** [comment]
I think I found the issue in `stats.py` only name and counter are being returned by `.filter(counter__gt=0).values('name','counter').order_by('-counter')[:10])`.

We either need to add description to that or modify `schoolstats_voucherusage.html` to take out `e.voucherId`, `e.description`, and add `e.name`. Any preference how you would like me to proceed @leetucker?

**Comment by leetucker** [comment]
Hey @afs2015 , I requested what I think is the right approach (passing voucherId and name, but not description) as changes to your pull request.  It sounds like once that's done the issue should be all set for now.
