### ISSUE TITLE
Local Installation for Development - File not found

### ISSUE THREAD

**Issue by afs2015** [django-danceschool/django-danceschool#127]
Attempting to run the code below [from Step 4 here](https://django-danceschool.readthedocs.io/en/latest/installation_development.html)

`django-admin startproject --template https://raw.githubusercontent.com/django-danceschool/development-template/archive/master.zip`

results in this error

`CommandError: couldn't download URL https://raw.githubusercontent.com/django-danceschool/development-template/archive/master.zip to master.zip: HTTP Error 404: Not Found`

**Comment by afs2015** [comment]
Okay found the issue, the documentation has the wrong link. The file should be found here:

`https://github.com/django-danceschool/development-template/archive/master.zip`

**Comment by afs2015** [comment]
@leetucker: I updated the documentation in master, is there anything we have to do to make [it update here](https://django-danceschool.readthedocs.io/en/latest/installation_development.html) as well? It's still showing the wrong https://raw.githubusercontent.com in the documentation.

**Comment by afs2015** [comment]
Hmm, i'm seeing why it might have been hosted somewhere else:

Trying to run `django-admin startproject --template https://github.com/django-danceschool/development-template/archive/master.zip testDanceschool` 

resulted in:

 `CommandError: couldn't download URL https://github.com/django-danceschool/development-template/archive/master.zip to master.zip: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719)>`

**Comment by leetucker** [comment]
@afs2015 : The ReadTheDocs website should automatically update whenever the documentation is updated in master.  Feel free to add whatever documentation you think is necessary for the Mac-specific issue, maybe just a link to the relevant StackOverflow page?)

**Comment by afs2015** [comment]
@leetucker: Made changes incorporating your suggestions for Step 4 and marking this as closed.
