### ISSUE TITLE
Huey version 2.0 changed its SQLite API

### ISSUE THREAD

**Issue by riclima** [django-danceschool/django-danceschool#140]
On Huey 2.0, Sqlite Huey was moved to the `huey` namespace, causing the line
https://github.com/django-danceschool/django-danceschool/blob/71aedba2ef783f8c745dc63653e0918fb5638fbc/danceschool/default_settings.py#L10
to throw an error.

Two very simple possible solutions: change the line to `from huey import SqliteHuey` and set the Huey minimum version to 2.0, or set the maximum version lower than 2.0.

**Comment by leetucker** [comment]
I propose that we set the maximum version lower than 2.0 in the next minor release (0.8.5), which I intend to release as soon as we solve #139 and I finish another couple of minor fixes.  This will give us time to figure out whether our other uses of Huey are optimized for Huey 2.0, and that there are no other changes that cause issues.  Then, we can update the dependency to 2.0 for the 0.9.0 release.

I'll commit the change to requirements.txt and setup.py requiring huey<2.0 for now.

**Comment by riclima** [comment]
Good plan.

**Comment by afs2015** [comment]
@leetucker: Just to confirm progress on this ticket in #140 you pinned Huey to version <2.0 to avoid compatibility issues. and this was in version 0.8.5.

As part of the 0.9.0 version release we will update the dependency to Huey 2.0.

**Comment by leetucker** [comment]
The dependency has been updated to Huey 2.0+ with the 0.9.0 release, so I am closing this.
