### ISSUE TITLE
Expense Item save fails when user does not have permission to Mark Expenses Paid at Time Of Submission

### ISSUE THREAD

**Issue by mayoroftuesday** [django-danceschool/django-danceschool#143]
In financial/forms.py in ExpenseReportingForm.__init__(), if the user has permission mark_expenses_paid, it renders a section where there user can enter a accrualDate. This value is automatically populated using the current timezone.

Without that permission, the field is not created and remains NULL. I can't tell exactly where the issue is, but if accrualDate is NULL, something is crashing in the ExpenseItem.save() function in financial/models.py, causing the save to fail.

Could be here:
```
        # Set the accrual date.  The method for series/events ensures that the accrualDate month
        # is the same as the reported month of the event/series by accruing to the start date of the first
        # occurrence in that month.
        if not self.accrualDate:
            if self.invoiceItem and self.invoiceItem.finalEventRegistration:
                min_event_time = self.invoiceItem.finalEventRegistration.event.eventoccurrence_set.filter(**{'startTime__month':self.invoiceItem.finalEventRegistration.event.month}).first().startTime
                self.accrualDate = min_event_time
            elif self.event:
                self.accrualDate = self.event.eventoccurrence_set.order_by('startTime').filter(**{'startTime__month': self.event.month}).last().startTime
            elif self.invoiceItem:
                self.accrualDate = self.invoiceItem.invoice.creationDate
            elif self.receivedDate:
                self.accrualDate = self.receivedDate
            elif self.submissionDate:
                self.accrualDate = self.submissionDate
            else:
                self.submissionDate = timezone.now()
                self.accrualDate = self.submissionDate
```

**Comment by afs2015** [comment]
Had another user today unable to login due to not having the permission `mark_expenses_paid`.

**Comment by leetucker** [comment]
@mayoroftuesday @afs2015 I have replicated this bug locally and I'm looking into it now.

**Comment by leetucker** [comment]
Turns out the issue was simpler than I thought. The accrualDate hidden field on the form was only being added to the form if the user had mark_expenses_paid permissions, even though it should be added for all users.  Since accrualDate is a required field, that caused the form not to validate.  I moved the hidden field so that it is always created.
