### ISSUE TITLE
Remove "oneTimeSeries" flag from ClassDescription and implement ClassDescription autocomplete

### ISSUE THREAD

**Issue by leetucker** [django-danceschool/django-danceschool#145]
The oneTimeSeries flag was designed to prevent clutter in the Series admin by not showing ClassDescriptions that will never again be offered.  However, in practice this confuses users because they cannot see the description that they are looking for, and are not used to going into the admin to find it and uncheck the box for a one-time series.  A better solution is to include all ClassDescriptions in the Series admin, but to populate choices using an autocomplete.  This makes it easier to find what the user wants without clutter.  I'm working on this now and should have it committed to master shortly.

The oneTimeSeries flag is not used for anything else (and I don't know of any other obvious use for it), so I will remove it from the database schema with the next major update.

**Comment by afs2015** [comment]
@leetucker: This seems great, my only concern would be testing that with autocomplete it doesn't make it difficult to search through ClassDescriptions that are duplicated such as multiple Lindy 1s.

**Comment by leetucker** [comment]
@afs2015 Fair point.  I'm going to experiment with adding context to the autocomplete options, something like the last time it was offered.  That will hopefully make it easier to select the right ClassDescription even when they have the same name.

**Comment by leetucker** [comment]
OK, the admin updates are all done and changes are pushed to master.  The autocomplete indicates the last time that the class series was offered.  One can always click the "Edit" button to look at the full description text if there is any confusion beyond that.

**Comment by afs2015** [comment]
Sounds good @leetucker, we can mark this as closed unless if you want to keep it open for some reason.

**Comment by afs2015** [comment]
Marking this as closed.
