### ISSUE TITLE
[Bug] Migration failing for OneToOneField(StaffMember)

### ISSUE THREAD

**Issue by mihailb** [django-danceschool/django-danceschool#148]
Migration failing with:
>   File "/usr/lib/python3.7/site-packages/danceschool/private_lessons/models.py", line 17, in InstructorPrivateLessonDetails
>     instructor = models.OneToOneField(StaffMember)
> NameError: name 'StaffMember' is not defined

See:
https://github.com/django-danceschool/django-danceschool/blob/db15e2cb81c32a512fc9476f5a93c7022594d70f/danceschool/private_lessons/models.py#L17

**Comment by afs2015** [comment]
To clarify is this when you are doing the initial migrations for this project? Thanks!

**Comment by mihailb** [comment]
@afs2015 yes, if you'll open the model I sent above - you'll see usage of `models.OneToOneField(StaffMember)` but `StaffMember` is not imported..

**Comment by afs2015** [comment]
Thanks @mihailb, @leetucker do you have any insight on this? If I have time in the next week or two i'm going to try to replicate this issue.

**Comment by leetucker** [comment]
Hi @mihailb , I'm sorry that this issue sat unaddressed for so long.  I just added the missing import to `private_lessons/models.py`.  I will also be closing this issue.

The private lessons app has not been in use by the various schools that I am aware of that are using the project actively.  So, if you encounter additional bugs, please do not hesitate to let us know about them.  Now that the 0.9.x series is released, I hope to be able to remain more on top of issues like this.
