### ISSUE TITLE
Registration Success Emails do not contain information about class registrations

### ISSUE THREAD

**Issue by afs2015** [django-danceschool/django-danceschool#151]
The email is sent out using template `django-danceschool/danceschool/core/templates/email/registration_success.html` after a successful registration is currently not containing class information as shown in the screenshot below.

<img width="1182" alt="Screen Shot 2021-09-02 at 9 25 26 PM" src="https://user-images.githubusercontent.com/1641767/131936905-41202f31-f00a-452c-9e7b-ae5f82eb0656.png">

**Comment by afs2015** [comment]
From the code it seems like the first template tag `{{ first_name }}` and this entire block is not being read in

`{% for event in eventList %}{{ event.title}}, begins {{ event.start|date:"l, F jS, g:i A" }}
{% endfor %}

{% if invoice %}Net amount paid: {{ currencySymbol }}{{ invoice.amountPaid|floatformat:2 }}
{% if invoice.outstandingBalance %}Outstanding balance: {{ currencySymbol }}{{ invoice.outstandingBalance|floatformat:2 }}
View Invoice/Make Payments: {{ invoice.url }}{% endif %}{% endif %}{% if registrationComments %}Your comments:
{{ registrationComments }}`

**Comment by afs2015** [comment]
Tested this using a voucher with no money and a class that costs $1 and still got the same result.

**Comment by leetucker** [comment]
@afs2015 What version are you running?  I'm looking at the current master and it looks like the code you posted is out of date.  When the registration-invoice relationship was refactored, the template format changed.  You can see most of the changes as of commit [984cba99265f6148198aa3d9d8fc8bb7a198728f](https://github.com/django-danceschool/django-danceschool/commit/984cba99265f6148198aa3d9d8fc8bb7a198728f#diff-2077bd4a27b25f682707dcd58ca440d49c2804b38491d4a6bcbd6b1625b2ab04).

**Comment by afs2015** [comment]
@leetucker: We are using version `0.9.3` on the Boston Lindy Hop website which you upgraded it to back in May 2021. I believe my local repo for DjangoDanceSchool was out of date.

I updated my local repo and I believe this is the code that is not firing:

`{% for item in itemList %}
{% if item.eventRegistration %}{{ item.eventRegistration.event.title}}, begins {{ item.eventRegistration.event.start|date:"l, F jS, g:i A" }}{% else %}{{ item.description }}{% endif %}{% endfor %}

Total, Net of Discounts: {{ currencySymbol }}{{ total|floatformat:2 }}{% if taxes %}
Taxes: {{ currencySymbol }}{{ taxes|floatformat:2 }}{% endif %}{% if adjustments %}
Adjustments/Refunds: {{ currencySymbol }}{{ adjustments|floatformat:2 }}{% endif %}

{% if thisPaymentAmount %}This Payment Amount: {{ currencySymbol }}{{ thisPaymentAmount|floatformat:2 }}
{% endif %}Total Amount paid: {{ currencySymbol }}{{ amountPaid|floatformat:2 }}
Outstanding balance: {{ currencySymbol }}{{ outstandingBalance|floatformat:2 }}
View Invoice/Make Payments: {{ url }}{% if registrationComments %}Your comments:
{{ registrationComments }}`

**Comment by afs2015** [comment]
@leetucker: Did you ever managed to resolve this issue or is NCS still having this registration email problem?

**Comment by sheromon** [comment]
Ah, this bug. You must have had so many people mention it. Yeah, so I'm not much a web developer, and I have no experience with django, so I'm probably not the best person to help. But what I do have is a registration email from NCS from August 2022. It looks like this. Differences seem to be that my name is filled in, and although there is still no class title, the link links to the webpage with the class description, so I can tell which class it is by clicking on the link.

![Screenshot from 2023-08-27 22-12-33](https://github.com/django-danceschool/django-danceschool/assets/14807087/46e8679f-4b97-4c06-b966-494be841e181)

Edit: Even though this isn't my wheelhouse, looking at the email template in the latest commit on master, I feel like there is nothing to add a hyperlink, so I'm guessing the NCS email template is not at that version...

**Comment by afs2015** [comment]
Closing this ticket. The issue was patched by git+git://github.com/django-danceschool/django-danceschool.git@65ae09ffdcb0821e82df0e1f634fe13c0384a525. We just had to update our template by following the instructions here: https://django-danceschool.readthedocs.io/en/latest/customization_basic.html
