### ISSUE TITLE
make referral codes support referral links

### ISSUE THREAD

**Issue by NorthIsUp** [django-danceschool/django-danceschool#71]
make a referral link for registration that will set a cookie and give credit for those who use it.

**Comment by leetucker** [comment]
I think this is already possible.  Specifically, if my referral code is OMGWTFBBQ, then typing in http://mysite.com/register/referral/OMGWTFBBQ/ should cause the referral code to be entered automatically in step 2.

**Comment by leetucker** [comment]
Closing this, since as far as I can tell there is no outstanding issue here.
