### ISSUE TITLE
users confused if discount actually is working

### ISSUE THREAD

**Issue by NorthIsUp** [django-danceschool/django-danceschool#79]
since the discount doesn't show up until the final stage in payments we have had several users contact us saying "the discount isn't working"

Suggested fix is to also display the discount on the cart page.

here discount is a point based one for taking two classes.

**Comment by afs2015** [comment]
I agree with @NorthIsUp, a good solution is to display the discount on the cart page.

**Comment by leetucker** [comment]
OK, this is implemented.  Some discrepancies can still happen if people's answers to the info form make them eligible for additional discounts (e.g. new customer discounts and student discounts).  However, the price can only go down or stay the same between the cart page and the final page of the registration process.
