### ISSUE TITLE
Segmentation fault with Python 3.6

### ISSUE THREAD

**Issue by schindld** [django-danceschool/django-danceschool#91]
Trying to install django-danceschool with latest python version seems to work until starting the server. Running `python manage.py runserver` gives an error:
```
Performing system checks...

Segmentation fault
```
Downgrading to python and python-dev 3.5.2 is the only way I've found to make it work.

**Comment by afs2015** [comment]
Thanks for the heads up, is there any more detail in the traceback besides the Segmentation fault? I'll try to recreate this when I get the chance.

**Comment by leetucker** [comment]
I've got things running on Python 3.6, though it is in a Docker stack.  If you've got more info on your setup, I'd be happy to investigate more.

**Comment by leetucker** [comment]
@schindld I'm going to close this ticket, since this doesn't seem to be a general issue with use of Python 3.6, but if you're still having trouble with your setup, let me know and I can help diagnose it.
