### ISSUE TITLE
Enabling private_lessons module causes db migration error

### ISSUE THREAD

**Issue by schindld** [django-danceschool/django-danceschool#92]
Starting fresh with no sqlite file, if I uncomment the private_lessons module line in settings.py and run `python manage.py migrate`, it fails. If I leave it commented out, migration works. Here's the error when it fails:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: core_dancerole
```
I'm using version 0.5.5.

**Comment by schindld** [comment]
From the rest of the stack trace, it looks like this is the line of code that causes the above result: 
`File "/web/danceschool/private_lessons/forms.py", line 33, in SlotBookingForm
    role = forms.ChoiceField(label=_('Dance role'),choices=[(x.id, x.name) for x in DanceRole.objects.all()])`

**Comment by afs2015** [comment]
@schindld thanks for the heads up! @leetucker any idea what could be causing this?

**Comment by leetucker** [comment]
The private_lessons app's initial migration appears to depend on the core app's migration '0016_auto_20170830_1159', so the DanceRole model should be written into the DB by the time that private_lessons migrations are set up.  Must be the forms.py code is getting executed before the migration is run? I can take a look into this, but it may take me a few days (still getting my home office set up).

**Comment by leetucker** [comment]
OK, this was fixed by changing this filed to a ModelChoiceField (which specifies a queryset but isn't called on startup) instead of a ChoiceField with manually populated choices.

The change is rolled into the 0.6.0-dev branch for now, but will go in the next release.

Thanks @schindld for letting me know about this one.
